user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /yab

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /yab/resetting

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /yab
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /yab
